const test = require("node:test");
const assert = require("node:assert/strict");
const {cleanName, cleanWord, cleanPhrase, similar, __test} = require("../server");
test("normalizes game words", () => assert.equal(cleanWord(" tiger! "), "TIGER"));
test("removes markup from names", () => assert.equal(cleanName("<TM>"), "TM"));
test("normalizes survey phrases", () => assert.equal(cleanPhrase("  Sun-Cream! "), "suncream"));
test("accepts close survey variants", () => assert.equal(similar("towels", "towel"), true));
test("Word Link pressure timer tightens with remaining players",()=>{const room=count=>({players:Array.from({length:count},(_,i)=>({id:String(i),eliminated:false}))});assert.equal(__test.wordTurnSeconds(room(4)),15);assert.equal(__test.wordTurnSeconds(room(3)),10);assert.equal(__test.wordTurnSeconds(room(2)),7)});
test("Word Link rejects words shorter than four letters",()=>{assert.equal(__test.validWordLength("cat"),false);assert.equal(__test.validWordLength("lion"),true)});
test("records captured Royal Race tokens for the return animation", () => {
	const room = {
		players:[
			{id:"a",name:"A",royalColor:"gold",royalKicked:false},
			{id:"b",name:"B",royalColor:"blue",royalKicked:false}
		],
		phase:"royal",royalOrder:["a","b"],royalTurn:0,royalLegal:[0],royalDice:1,
		royalTokens:{a:[0,-1,-1,-1],b:[40,-1,-1,-1]},royalPlacements:[],royalMoveSeq:0
	};
	assert.equal(__test.royalMove(room,"a",0),true);
	assert.equal(room.royalTokens.b[0],-1);
	assert.deepEqual(room.royalLastMove.capturedTokens,[{playerId:"b",tokenIndex:0,fromProgress:40,toProgress:-1}]);
});
test("Royal Race goes directly from the final track square to the crown",()=>{
	const room={players:[{id:"a",name:"A",royalColor:"gold",royalKicked:false},{id:"b",name:"B",royalColor:"blue",royalKicked:false}],phase:"royal",royalOrder:["a","b"],royalTurn:0,royalLegal:[0],royalDice:1,royalTokens:{a:[51,-1,-1,-1],b:[-1,-1,-1,-1]},royalPlacements:[],royalMoveSeq:0};
	assert.deepEqual(__test.royalLegal(room,"a",1),[0]);
	assert.deepEqual(__test.royalLegal(room,"a",2),[]);
	assert.equal(__test.royalMove(room,"a",0),true);
	assert.equal(room.royalTokens.a[0],52);
	assert.equal(room.royalLastMove.reachedHome,true);
});
test("every Royal colour travels the same 52-square route with eight safe cells",()=>{for(const color of __test.ROYAL_COLORS){const track=Array.from({length:52},(_,progress)=>__test.royalTrack(color,progress));assert.equal(new Set(track).size,52);assert.equal(track.filter(square=>__test.ROYAL_SAFE.has(square)).length,8)}});
test("Royal safe squares prevent capture",()=>{const room={players:[{id:"a",name:"A",royalColor:"gold",royalKicked:false},{id:"b",name:"B",royalColor:"blue",royalKicked:false}],phase:"royal",game:"royal",royalOrder:["a","b"],royalTurn:0,royalLegal:[0],royalDice:1,royalTokens:{a:[7,-1,-1,-1],b:[47,-1,-1,-1]},royalPlacements:[],royalMoveSeq:0,deadline:0,message:"",resultsRecorded:false};assert.equal(__test.royalTrack("gold",8),8);assert.equal(__test.royalTrack("blue",47),8);__test.royalMove(room,"a",0);assert.equal(room.royalTokens.b[0],47);assert.equal(room.royalLastMove.captured,false)});
test("reaching the crown with one token awards a bonus turn",()=>{const room={players:[{id:"a",name:"A",royalColor:"gold",royalKicked:false},{id:"b",name:"B",royalColor:"blue",royalKicked:false}],phase:"royal",game:"royal",royalOrder:["a","b"],royalTurn:0,royalLegal:[0],royalDice:1,royalTokens:{a:[51,-1,-1,-1],b:[-1,-1,-1,-1]},royalPlacements:[],royalMoveSeq:0,deadline:0,message:"",resultsRecorded:false};__test.royalMove(room,"a",0);assert.equal(room.royalTokens.a[0],__test.ROYAL_HOME);assert.equal(room.royalOrder[room.royalTurn],"a");assert.match(room.message,/bonus roll/)});
function leaveRoom(phase="lobby"){
	const players=[{id:"a",name:"A",host:true,score:0,eliminated:false,royalKicked:false,connected:true,connectionStatus:"connected"},{id:"b",name:"B",host:false,score:0,eliminated:false,royalKicked:false,connected:true,connectionStatus:"connected"},{id:"c",name:"C",host:false,score:0,eliminated:false,royalKicked:false,connected:true,connectionStatus:"connected"}];
	return {code:"TEST",phase,hostId:"a",players,turn:0,timerSeconds:15,deadline:1,winnerId:null,guessed:new Set(),drawOrder:["a","b","c"],drawTurn:2,drawTotal:3,drawerId:"b",drawWord:"crown",strokes:[],lastGuesses:[],royalOrder:["a","b","c"],royalTurn:1,royalDice:null,royalLegal:[],royalTokens:{a:[-1,-1,-1,-1],b:[-1,-1,-1,-1],c:[-1,-1,-1,-1]},royalPlacements:[]};
}
test("a disconnected player keeps their protected seat and complete game state",()=>{const room=leaveRoom("royal"),player=room.players[1];player.score=73;room.royalTokens.b=[12,4,-1,-1];room.dealPersonal={b:17};assert.equal(__test.markPlayerDisconnected(room,"b",1000),true);assert.equal(player.connected,false);assert.equal(player.reconnectDeadline,1000+__test.RECONNECT_GRACE_MS);assert.equal(player.score,73);assert.deepEqual(room.royalTokens.b,[12,4,-1,-1]);assert.equal(room.dealPersonal.b,17);assert.equal(room.drawerId,"b");assert.equal(__test.markPlayerConnected(room,"b",2000),true);assert.equal(player.connected,true);assert.equal(player.reconnectDeadline,0);assert.equal(player.score,73);assert.deepEqual(room.royalTokens.b,[12,4,-1,-1])});
test("a player is removed only after the reconnect grace period expires",()=>{const room=leaveRoom("draw");__test.markPlayerDisconnected(room,"b",1000);assert.equal(__test.expireDisconnectedPlayers(room,1000+__test.RECONNECT_GRACE_MS-1),0);assert.ok(room.players.some(p=>p.id==="b"));assert.equal(__test.expireDisconnectedPlayers(room,1000+__test.RECONNECT_GRACE_MS),1);assert.ok(!room.players.some(p=>p.id==="b"));assert.equal(room.drawerId,"c")});
test("connection states progress from red reconnecting to grey disconnected and recover to green",()=>{const room=leaveRoom(),player=room.players[1];player.connectionStatus="connected";player.lastPresenceAt=1000;__test.markPlayerDisconnected(room,"b",2000);assert.equal(player.connectionStatus,"reconnecting");assert.equal(__test.refreshConnectionStatuses(room,11999),false);assert.equal(__test.refreshConnectionStatuses(room,12000),true);assert.equal(player.connectionStatus,"disconnected");__test.markPlayerConnected(room,"b",13000);assert.equal(player.connectionStatus,"connected")});
test("host control transfers temporarily and returns to the reconnecting owner",()=>{const room=leaveRoom();room.ownerId="a";__test.markPlayerDisconnected(room,"a",1000);assert.equal(room.hostId,"b");assert.equal(room.players.find(p=>p.id==="b").host,true);__test.markPlayerConnected(room,"a",2000);assert.equal(room.hostId,"a");assert.equal(room.players.find(p=>p.id==="a").host,true)});
test("a permanent host transfer prevents the former owner reclaiming control",()=>{const room=leaveRoom();room.ownerId="a";assert.equal(__test.transferHost(room,"b",{permanent:true}),true);assert.equal(room.ownerId,"b");__test.markPlayerDisconnected(room,"a",1000);__test.markPlayerConnected(room,"a",2000);assert.equal(room.hostId,"b")});
test("a connected player with stale presence becomes unstable",()=>{const room=leaveRoom(),player=room.players[1];player.connectionStatus="connected";player.lastPresenceAt=1000;assert.equal(__test.refreshConnectionStatuses(room,21001),true);assert.equal(player.connectionStatus,"unstable")});
test("three universal AFK misses remove an inactive player",()=>{const room=leaveRoom(),player=room.players[1];assert.equal(__test.markAfkMiss(room,player,"missed"),false);assert.equal(__test.markAfkMiss(room,player,"missed"),false);assert.equal(player.afkMisses,2);assert.equal(__test.markAfkMiss(room,player,"missed"),true);assert.ok(!room.players.some(p=>p.id==="b"))});
test("Away players are skipped without collecting AFK misses",()=>{const room=leaveRoom(),player=room.players[1];player.away=true;assert.equal(__test.markAfkMiss(room,player,"missed"),false);assert.equal(player.afkMisses,undefined);player.away=false;player.afkMisses=2;__test.markPlayerActivity(player);assert.equal(player.afkMisses,0)});
test("the lobby requires every connected present player to ready up",()=>{const room=leaveRoom();room.game="wordlink";assert.match(__test.readinessError(room),/READY/);room.players.forEach(p=>p.ready=true);assert.equal(__test.readinessError(room),"");room.players[1].away=true;assert.match(__test.readinessError(room),/connected, present and READY/)});
test("team readiness still enforces two members per Survey team",()=>{const room=leaveRoom();room.game="survey";room.mode="teams";room.players.forEach((p,i)=>{p.ready=true;p.team=i===0?"gold":"blue"});assert.match(__test.readinessError(room),/two players/);room.players.push({id:"d",name:"D",connected:true,ready:true,away:false,team:"gold"});assert.equal(__test.readinessError(room),"")});
test("a ready Word Link lobby begins with an authoritative deadline",()=>{const room=leaveRoom();room.game="wordlink";room.createdAt=1;room.players.forEach(p=>{p.ready=true;p.gameStats=__test.freshStats()});assert.equal(__test.beginConfiguredGame(room),true);assert.equal(room.phase,"playing");assert.ok(room.deadline>Date.now());assert.ok(room.players.every(p=>p.ready===false))});
test("leaving the lobby removes the player and transfers host",()=>{const room=leaveRoom();assert.equal(__test.removePlayer(room,"a"),true);assert.deepEqual(room.players.map(p=>p.id),["b","c"]);assert.equal(room.hostId,"b");assert.equal(room.players[0].host,true)});
test("a departing Draw & Guess artist is removed and the next artist starts",()=>{const room=leaveRoom("draw");__test.removePlayer(room,"b");assert.deepEqual(room.players.map(p=>p.id),["a","c"]);assert.equal(room.drawerId,"c");assert.equal(room.drawTurn,2)});
test("a departing Royal Race player is removed without skipping the next turn",()=>{const room=leaveRoom("royal");__test.removePlayer(room,"b");assert.deepEqual(room.royalOrder,["a","c"]);assert.equal(room.royalOrder[room.royalTurn],"c");assert.equal(room.royalTokens.b,undefined)});
test("spectators remain outside active game state and fill the next available seats",()=>{const room=leaveRoom("finished");room.players.push(...Array.from({length:4},(_,i)=>({id:`p${i}`,name:`P${i}`})));room.spectators=[{id:"s1",name:"S1",spectator:true},{id:"s2",name:"S2",spectator:true}];assert.equal(__test.participants(room).length,9);assert.equal(__test.promoteSpectators(room),1);assert.equal(room.players.length,8);assert.equal(room.players.at(-1).spectator,false);assert.deepEqual(room.spectators.map(p=>p.id),["s2"])});
test("end-game flow returns the same room to a clean lobby",()=>{const room=leaveRoom("finished");room.game="wordlink";room.returnDeadline=123;room.rematchVotes=["a","b"];room.spectators=[{id:"s",name:"Spectator",spectator:true,connected:true}];room.players.forEach(p=>{p.ready=true;p.score=20});__test.returnToLobby(room,"Rematch approved.");assert.equal(room.code,"TEST");assert.equal(room.phase,"lobby");assert.equal(room.returnDeadline,0);assert.deepEqual(room.rematchVotes,[]);assert.ok(room.players.some(p=>p.id==="s"&&!p.spectator));assert.ok(room.players.every(p=>!p.ready&&p.score===0))});
test("automatic drawing assist reduces stroke wobble while preserving endpoints",()=>{const input=[[0,0],[.25,.28],[.5,.47],[.75,.78],[1,1]],output=__test.smoothStrokePoints(input);assert.deepEqual(output[0],[0,0]);assert.deepEqual(output.at(-1),[1,1]);assert.ok(Math.abs(output[1][1]-.25)<Math.abs(input[1][1]-.25));assert.equal(output.length,input.length)});
test("Draw and Guess awards a clear maximum of ten points per guess",()=>{assert.equal(__test.calculateDrawScore(60000,true),10);assert.equal(__test.calculateDrawScore(30000,false),7);assert.equal(__test.calculateDrawScore(0,false),5)});
test("Draw and Guess accepts intelligent aliases without accepting tiny fragments",()=>{assert.equal(__test.drawGuessMatches("phone","telephone"),true);assert.equal(__test.drawGuessMatches("soccer ball","football"),true);assert.equal(__test.drawGuessMatches("bir","birthday cake"),false)});
test("drawing undo removes every network batch from the latest gesture",()=>{const room={strokes:[{strokeId:"one",points:[[0,0],[.1,.1]]},{strokeId:"two",points:[[.2,.2],[.3,.3]]},{strokeId:"two",points:[[.3,.3],[.4,.4]]}]};assert.equal(__test.undoDrawStroke(room),true);assert.deepEqual(room.strokes.map(s=>s.strokeId),["one"]);assert.equal(__test.undoDrawStroke({strokes:[]}),false)});
test("room chat strips markup and limits message length",()=>{assert.equal(__test.cleanChat("  <b>Hello</b>   room  "),"Hello room");assert.equal(__test.cleanChat("x".repeat(300)).length,180)});
test("room chat confirms retries without duplicating a message",()=>{const room={chat:[],chatSeq:0},player={id:"a",name:"A"};const first=__test.addChatMessage(room,player,"Hello","message-1"),retry=__test.addChatMessage(room,player,"Hello","message-1");assert.equal(first.id,retry.id);assert.equal(room.chat.length,1)});
test("game events are separated from player chat and deduplicated",()=>{const room={chat:[],chatSeq:0,lastEventMessage:""};assert.equal(__test.addGameEvent(room,"A rolled six").type,"event");assert.equal(__test.addGameEvent(room,"A rolled six"),null);assert.equal(room.chat.length,1)});
test("host chat moderation supports mute and five-second slow mode",()=>{const room={hostId:"host",chatSlowMode:true},host={id:"host"},player={id:"p",lastChatAt:1000};assert.equal(__test.canSendChat(room,host,2000),"");assert.match(__test.canSendChat(room,player,3000),/five seconds/);assert.equal(__test.canSendChat(room,player,6000),"");player.chatMuted=true;assert.match(__test.canSendChat(room,player,9000),/muted/)});
test("players can receive voice while their own microphone is off",()=>{const listener={id:"a",voiceOn:false,connected:true},speaker={id:"b",voiceOn:true,connected:true};assert.equal(__test.voiceRecipientAvailable(speaker,listener),true);assert.equal(__test.voiceRecipientAvailable(listener,speaker),true);assert.equal(__test.voiceRecipientAvailable(listener,listener),false);assert.equal(__test.voiceRecipientAvailable(listener,{id:"c",connected:false}),false)});
test("Survey Showdown schedules the next 60-second question automatically",()=>{const room={phase:"survey",deadline:1,surveyIndex:0,surveyQuestions:[{},{},{}],mode:"ffa",players:[{id:"a",score:10}],found:new Set(),round:1};__test.finishSurveyQuestion(room);assert.equal(room.phase,"survey-break");assert.ok(room.deadline>Date.now());assert.match(room.message,/automatically/);const before=Date.now();__test.startNextSurvey(room);assert.equal(room.phase,"survey");assert.equal(room.surveyIndex,1);assert.ok(room.deadline-before>=__test.SURVEY_ROUND_MS-50)});
test("Survey Showdown uses one consistent alias matcher",()=>{const question={answers:[{text:"Watching TV",aliases:["television"]},{text:"Cooking",aliases:["making food"]}]};assert.equal(__test.findSurveyAnswer(question,"watch tv"),0);assert.equal(__test.findSurveyAnswer(question,"making food"),1);assert.equal(__test.findSurveyAnswer(question,"television",new Set([0])),-1)});
test("Survey Showdown rejects answers at the authoritative deadline",()=>{const room={phase:"survey",deadline:1000};assert.equal(__test.surveyDeadlineOpen(room,999),true);assert.equal(__test.surveyDeadlineOpen(room,1000),false);assert.equal(__test.surveyDeadlineOpen(room,1001),false)});
test("Draw and Guess schedules the next artist automatically",()=>{const room={phase:"draw",deadline:1,drawWord:"crown",drawTurn:1,drawTotal:2,drawOrder:["a","b"],players:[{id:"a",name:"A",score:0},{id:"b",name:"B",score:0}],strokes:[],guessed:new Set(),lastGuesses:[]};__test.finishDrawTurn(room);assert.equal(room.phase,"draw-break");assert.ok(room.deadline>Date.now());assert.match(room.message,/automatically/)});
test("completed games compile normalized XP into the Champions Board",()=>{const players=[{id:"a",name:"A",score:900,totalXp:0,wins:0,gamesPlayed:0,gameStats:__test.freshStats()},{id:"b",name:"B",score:300,totalXp:0,wins:0,gamesPlayed:0,gameStats:__test.freshStats()}],room={phase:"finished",game:"draw",mode:"ffa",winnerId:"a",players,royalPlacements:[],resultsRecorded:false};__test.recordResults(room);assert.equal(players[0].wins,1);assert.ok(players[0].totalXp>players[1].totalXp);assert.equal(__test.leaderboard(room)[0].id,"a");assert.equal(room.resultsRecorded,true)});
test("registered players earn persistent coins while guests earn temporary XP only",()=>{const players=[{id:"a",accountId:"account-a",name:"A",score:50,coinBalance:100,totalXp:0,wins:0,gamesPlayed:0,gameStats:__test.freshStats()},{id:"b",accountId:null,name:"B",score:20,coinBalance:0,totalXp:0,wins:0,gamesPlayed:0,gameStats:__test.freshStats()}],room={code:"COINS",matchId:"match-1",phase:"finished",game:"draw",mode:"ffa",winnerId:"a",players,royalPlacements:[],resultsRecorded:false};__test.recordResults(room);assert.equal(players[0].coinBalance,200);assert.equal(players[1].coinBalance,0);assert.equal(room.lastResults[0].coins,100);assert.equal(room.lastResults[1].coins,0)});
test("completed results cannot award Royal prizes twice",()=>{const players=[{id:"a",accountId:"account-a",name:"A",score:4,coinBalance:100,totalXp:0,wins:0,gamesPlayed:0,gameStats:__test.freshStats()},{id:"b",accountId:"account-b",name:"B",score:1,coinBalance:100,totalXp:0,wins:0,gamesPlayed:0,gameStats:__test.freshStats()}],room={code:"ROYAL",matchId:"royal-1",phase:"finished",game:"royal",mode:"ffa",winnerId:"a",players,royalPlacements:["a","b"],resultsRecorded:false};__test.recordResults(room);const balances=players.map(p=>p.coinBalance),xp=players.map(p=>p.totalXp);__test.recordResults(room);assert.deepEqual(players.map(p=>p.coinBalance),balances);assert.deepEqual(players.map(p=>p.totalXp),xp)});
function dealRoom(){const players=[{id:"a",name:"A",score:0,dealStatus:"playing",dealPayout:0,totalXp:0,wins:0,gamesPlayed:0,gameStats:__test.freshStats()},{id:"b",name:"B",score:0,dealStatus:"playing",dealPayout:0,totalXp:0,wins:0,gamesPlayed:0,gameStats:__test.freshStats()}];return {code:"DEAL",game:"deal",mode:"ffa",phase:"deal-pick",players,dealCases:Array.from({length:26},(_,i)=>({number:i+1,value:i+1,opened:false,ownerId:null})),dealOrder:["a","b"],dealTurn:0,dealOpenRemaining:0,dealPersonal:{},dealOffers:{},dealChoices:{},dealRound:0,dealTurnsInCycle:0,dealBankerStage:"idle",dealFinalBank:false,royalPlacements:[],resultsRecorded:false,deadline:0,message:""}}
test("Deal or No Deal locks one personal case per player then starts opening",()=>{const room=dealRoom();assert.equal(__test.selectDealCase(room,"a",10),true);assert.equal(room.dealCases[9].ownerId,"a");assert.equal(room.dealTurn,1);assert.equal(__test.selectDealCase(room,"b",20),true);assert.equal(room.phase,"deal-open");assert.equal(room.dealOpenRemaining,1);assert.equal(room.dealOrder[room.dealTurn],"a")});
test("Deal or No Deal rotates after each player opens one case",()=>{const room=dealRoom();__test.selectDealCase(room,"a",10);__test.selectDealCase(room,"b",20);assert.equal(__test.openDealCase(room,1),true);assert.equal(room.dealOrder[room.dealTurn],"b");assert.equal(room.dealOpenRemaining,1);assert.equal(__test.openDealCase(room,2),true);assert.equal(room.phase,"deal-bank")});
test("Deal or No Deal final reveal pays deals or personal case values",()=>{const room=dealRoom();room.phase="deal-open";room.dealCases[9].ownerId="a";room.dealPersonal.a=10;room.dealCases[19].ownerId="b";room.dealPersonal.b=20;room.players[1].dealStatus="dealt";room.players[1].dealPayout=500;room.dealCases[9].value=250000;__test.finishDealGame(room);assert.equal(room.phase,"finished");assert.equal(room.players[0].score,250000);assert.equal(room.players[1].score,500);assert.equal(room.winnerId,"a")});
test("the banker becomes more generous as Deal or No Deal progresses",()=>{const room=dealRoom(),early=__test.dealOfferMetrics(room);room.dealCases.slice(0,13).forEach(item=>item.opened=true);const late=__test.dealOfferMetrics(room);assert.ok(late.generosity>early.generosity);assert.equal(late.progress,.5);assert.ok(early.risk>0);assert.equal(late.casesRemaining,13);room.dealFinalBank=true;assert.ok(__test.dealOfferMetrics(room).generosity>late.generosity)});
